### ISSUE TITLE
[Usage Request] Open Sourcing?

### ISSUE THREAD

**Issue by JaceyPenny** [EFanZh/efanzh.github.io#1]
Hey EFanZH,

I was wondering if you'd consider adding an open-source license of some kind to the code under `tools/ascii-tree-graph-generator`. I find it very useful and would like to make private modifications.

Let me know!

**Comment by JaceyPenny** [comment]
@EFanZh Just bumping this thread, please let me know if you're open to adding a license to this code, thanks!

**Comment by EFanZh** [comment]
I am OK with releasing the source code with some kind of open-source license, but currently this is not a formal project. I think I should move the source code into a new repository before releasing.

**Comment by JaceyPenny** [comment]
Sweet! I'll be on the lookout for it, assuming you decide to go that route. Thanks for getting back.

**Comment by EFanZh** [comment]
I have created a new repository: https://github.com/EFanZh/tree-graph-generator, and moved the sources into that repository.
